name: PR Validation

run-name: "👷🚧[#${{ github.run_number }}][VALIDATION] Validating PR \"${{ github.event.pull_request.title }}\""

on:
  pull_request:
    types: [ opened, ready_for_review, reopened ]

jobs:
  build:
    runs-on: ubuntu-latest
    name: "Validate PR 🔖"
    steps:
      - name: "Auto Assign PR"
        uses: kentaro-m/auto-assign-action@v2.0.0
